# Generated by Django 5.2.14 on 2026-05-30 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("path", models.CharField()),
                ("script", models.CharField()),
                ("secret", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="EnvVar",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("value", models.CharField()),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webhooks.webhook",
                    ),
                ),
            ],
        ),
    ]
