# Generated by Django 5.2.14 on 2026-05-30 06:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_alter_webhook_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="script",
            field=models.CharField(blank=True),
        ),
    ]
