# Generated by Django 5.2.14 on 2026-05-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_alter_webhook_id_alter_webhook_script"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envvar",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
